# Generated by Django 3.2.8 on 2021-10-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='preference',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
