# Generated by Django 3.2.8 on 2021-10-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resumeid',
            field=models.CharField(default='2gey783hn', max_length=10),
            preserve_default=False,
        ),
    ]
