# Generated by Django 3.2.8 on 2021-10-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_validity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
