# Generated by Django 3.2.8 on 2021-10-12 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_profile_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscription_validity',
            field=models.DateTimeField(default=datetime.datetime(2000, 6, 1, 0, 0)),
        ),
    ]
